#!/usr/bin/env python

import random

def main():
    print("Guess the number?")

    x=random.randint(1,100)
    guess = int

    while x != guess:
        guess = int( input ("pick a number 1-100"))

        if x == guess:
            print ("You are genius")
        elif x > guess:
            print ("try a bigger number")
        elif x < guess:
            print ("try a smaller number")

    
main()
